fc_parameters = {'lon': {'quantile': [{'q': 0.1},
   {'q': 0.2},
   {'q': 0.3},
   {'q': 0.9},
   {'q': 0.7},
   {'q': 0.8}],
  'minimum': None,
  'maximum': None,
  'agg_linear_trend': [{'f_agg': 'min', 'chunk_len': 50, 'attr': 'intercept'}],
  'median': None,
  'abs_energy': None,
  'fft_coefficient': [{'coeff': 58, 'attr': 'angle'}],
  'approximate_entropy': [{'m': 2, 'r': 0.1}],
  'cwt_coefficients': [{'widths': (2, 5, 10, 20), 'coeff': 14, 'w': 20}],
  'mean': None,
  'sum_of_reoccurring_data_points': None,
  'sample_entropy': None},
 'lat': {'maximum': None,
  'quantile': [{'q': 0.9},
   {'q': 0.1},
   {'q': 0.7},
   {'q': 0.6},
   {'q': 0.2},
   {'q': 0.8},
   {'q': 0.4}],
  'minimum': None,
  'number_cwt_peaks': [{'n': 1}],
  'sum_values': None,
  'abs_energy': None,
  'autocorrelation': [{'lag': 5}],
  'cwt_coefficients': [{'widths': (2, 5, 10, 20), 'coeff': 0, 'w': 2}],
  'spkt_welch_density': [{'coeff': 8}],
  'agg_linear_trend': [{'f_agg': 'max',
    'chunk_len': 50,
    'attr': 'intercept'}]},
 '速度': {'number_crossing_m': [{'m': 1}],
  'ratio_beyond_r_sigma': [{'r': 0.5}],
  'approximate_entropy': [{'m': 2, 'r': 0.9}],
  'partial_autocorrelation': [{'lag': 7}, {'lag': 6}, {'lag': 5}],
  'agg_autocorrelation': [{'f_agg': 'median', 'maxlag': 40}],
  'ar_coefficient': [{'k': 10, 'coeff': 1}],
  'fft_coefficient': [{'coeff': 5, 'attr': 'angle'}],
  'quantile': [{'q': 0.7}],
  'change_quantiles': [{'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.2}],
  'fft_aggregated': [{'aggtype': 'variance'}]},
 '方向': {'quantile': [{'q': 0.9}],
  'approximate_entropy': [{'m': 2, 'r': 0.1}],
  'ratio_beyond_r_sigma': [{'r': 0.5}],
  'fft_coefficient': [{'coeff': 5, 'attr': 'angle'}],
  'agg_autocorrelation': [{'f_agg': 'var', 'maxlag': 40}]}}