fc_parameters = {'lat': {'quantile': [{'q': 0.9},
   {'q': 0.8},
   {'q': 0.3},
   {'q': 0.6},
   {'q': 0.2},
   {'q': 0.7},
   {'q': 0.1},
   {'q': 0.4}],
  'maximum': None,
  'minimum': None,
  'number_cwt_peaks': [{'n': 1}],
  'fft_coefficient': [{'coeff': 5, 'attr': 'real'},
   {'coeff': 74, 'attr': 'angle'},
   {'coeff': 5, 'attr': 'angle'},
   {'coeff': 66, 'attr': 'angle'},
   {'coeff': 93, 'attr': 'angle'},
   {'coeff': 10, 'attr': 'imag'},
   {'coeff': 15, 'attr': 'real'},
   {'coeff': 10, 'attr': 'real'},
   {'coeff': 94, 'attr': 'angle'},
   {'coeff': 86, 'attr': 'angle'},
   {'coeff': 96, 'attr': 'angle'},
   {'coeff': 9, 'attr': 'angle'},
   {'coeff': 91, 'attr': 'angle'},
   {'coeff': 83, 'attr': 'angle'},
   {'coeff': 88, 'attr': 'angle'},
   {'coeff': 99, 'attr': 'angle'},
   {'coeff': 73, 'attr': 'angle'}],
  'median': None,
  'abs_energy': None,
  'cwt_coefficients': [{'widths': (2, 5, 10, 20), 'coeff': 7, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 14, 'w': 5},
   {'widths': (2, 5, 10, 20), 'coeff': 6, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 5, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 1, 'w': 20},
   {'widths': (2, 5, 10, 20), 'coeff': 1, 'w': 10},
   {'widths': (2, 5, 10, 20), 'coeff': 14, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 13, 'w': 5},
   {'widths': (2, 5, 10, 20), 'coeff': 0, 'w': 20},
   {'widths': (2, 5, 10, 20), 'coeff': 0, 'w': 5},
   {'widths': (2, 5, 10, 20), 'coeff': 11, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 9, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 8, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 0, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 1, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 10, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 2, 'w': 20},
   {'widths': (2, 5, 10, 20), 'coeff': 4, 'w': 10},
   {'widths': (2, 5, 10, 20), 'coeff': 4, 'w': 20},
   {'widths': (2, 5, 10, 20), 'coeff': 1, 'w': 5}],
  'percentage_of_reoccurring_datapoints_to_all_datapoints': None,
  'spkt_welch_density': [{'coeff': 8}, {'coeff': 5}],
  'longest_strike_above_mean': None,
  'approximate_entropy': [{'m': 2, 'r': 0.1},
   {'m': 2, 'r': 0.7},
   {'m': 2, 'r': 0.3}],
  'ratio_beyond_r_sigma': [{'r': 2.5}, {'r': 1.5}, {'r': 2}],
  'longest_strike_below_mean': None,
  'ar_coefficient': [{'k': 10, 'coeff': 3},
   {'k': 10, 'coeff': 4},
   {'k': 10, 'coeff': 2},
   {'k': 10, 'coeff': 0}],
  'change_quantiles': [{'f_agg': 'mean', 'isabs': False, 'qh': 0.2, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.2, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.4, 'ql': 0.2},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.2},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': False, 'qh': 0.4, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.6}],
  'agg_linear_trend': [{'f_agg': 'max', 'chunk_len': 50, 'attr': 'stderr'},
   {'f_agg': 'max', 'chunk_len': 50, 'attr': 'intercept'},
   {'f_agg': 'min', 'chunk_len': 50, 'attr': 'intercept'}],
  'partial_autocorrelation': [{'lag': 2},
   {'lag': 5},
   {'lag': 6},
   {'lag': 4},
   {'lag': 8}],
  'first_location_of_maximum': None,
  'index_mass_quantile': [{'q': 0.1}],
  'binned_entropy': [{'max_bins': 10}],
  'linear_trend': [{'attr': 'pvalue'}],
  'ratio_value_number_to_time_series_length': None,
  'sample_entropy': None,
  'skewness': None,
  'count_below_mean': None,
  'autocorrelation': [{'lag': 5}],
  'c3': [{'lag': 3}, {'lag': 2}],
  'mean': None,
  'last_location_of_minimum': None,
  'sum_of_reoccurring_values': None,
  'sum_values': None,
  'augmented_dickey_fuller': [{'attr': 'teststat'}],
  'cid_ce': [{'normalize': True}],
  'number_peaks': [{'n': 1}]},
 'lon': {'quantile': [{'q': 0.1},
   {'q': 0.2},
   {'q': 0.4},
   {'q': 0.9},
   {'q': 0.3},
   {'q': 0.8},
   {'q': 0.6},
   {'q': 0.7}],
  'minimum': None,
  'maximum': None,
  'change_quantiles': [{'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
   {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.6},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.2, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.2},
   {'f_agg': 'var', 'isabs': False, 'qh': 1.0, 'ql': 0.8}],
  'approximate_entropy': [{'m': 2, 'r': 0.1},
   {'m': 2, 'r': 0.3},
   {'m': 2, 'r': 0.9}],
  'fft_coefficient': [{'coeff': 64, 'attr': 'angle'},
   {'coeff': 58, 'attr': 'angle'},
   {'coeff': 99, 'attr': 'angle'},
   {'coeff': 2, 'attr': 'angle'},
   {'coeff': 5, 'attr': 'real'},
   {'coeff': 71, 'attr': 'angle'},
   {'coeff': 10, 'attr': 'real'},
   {'coeff': 73, 'attr': 'angle'},
   {'coeff': 85, 'attr': 'angle'},
   {'coeff': 89, 'attr': 'angle'},
   {'coeff': 70, 'attr': 'angle'},
   {'coeff': 79, 'attr': 'abs'},
   {'coeff': 1, 'attr': 'real'},
   {'coeff': 0, 'attr': 'real'}],
  'percentage_of_reoccurring_datapoints_to_all_datapoints': None,
  'cwt_coefficients': [{'widths': (2, 5, 10, 20), 'coeff': 0, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 2, 'w': 20},
   {'widths': (2, 5, 10, 20), 'coeff': 7, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 9, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 1, 'w': 20},
   {'widths': (2, 5, 10, 20), 'coeff': 13, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 6, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 14, 'w': 5},
   {'widths': (2, 5, 10, 20), 'coeff': 14, 'w': 20},
   {'widths': (2, 5, 10, 20), 'coeff': 11, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 1, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 8, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 14, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 10, 'w': 2}],
  'ar_coefficient': [{'k': 10, 'coeff': 1},
   {'k': 10, 'coeff': 3},
   {'k': 10, 'coeff': 2},
   {'k': 10, 'coeff': 4}],
  'median': None,
  'number_cwt_peaks': [{'n': 1}, {'n': 5}],
  'abs_energy': None,
  'binned_entropy': [{'max_bins': 10}],
  'sample_entropy': None,
  'agg_autocorrelation': [{'f_agg': 'median', 'maxlag': 40},
   {'f_agg': 'mean', 'maxlag': 40}],
  'agg_linear_trend': [{'f_agg': 'min', 'chunk_len': 50, 'attr': 'intercept'},
   {'f_agg': 'var', 'chunk_len': 50, 'attr': 'rvalue'},
   {'f_agg': 'mean', 'chunk_len': 50, 'attr': 'intercept'},
   {'f_agg': 'min', 'chunk_len': 50, 'attr': 'stderr'},
   {'f_agg': 'max', 'chunk_len': 50, 'attr': 'stderr'},
   {'f_agg': 'min', 'chunk_len': 10, 'attr': 'stderr'}],
  'mean': None,
  'partial_autocorrelation': [{'lag': 4},
   {'lag': 7},
   {'lag': 2},
   {'lag': 5},
   {'lag': 8},
   {'lag': 9},
   {'lag': 6}],
  'percentage_of_reoccurring_values_to_all_values': None,
  'sum_of_reoccurring_values': None,
  'cid_ce': [{'normalize': True}],
  'last_location_of_maximum': None,
  'longest_strike_above_mean': None,
  'ratio_value_number_to_time_series_length': None,
  'sum_of_reoccurring_data_points': None,
  'ratio_beyond_r_sigma': [{'r': 1}, {'r': 2.5}, {'r': 0.5}],
  'first_location_of_minimum': None,
  'number_peaks': [{'n': 1}],
  'count_above_mean': None,
  'last_location_of_minimum': None,
  'longest_strike_below_mean': None,
  'skewness': None,
  'autocorrelation': [{'lag': 2}]},
 '速度': {'number_crossing_m': [{'m': 1}],
  'quantile': [{'q': 0.7}, {'q': 0.8}, {'q': 0.6}, {'q': 0.9}],
  'ar_coefficient': [{'k': 10, 'coeff': 1},
   {'k': 10, 'coeff': 4},
   {'k': 10, 'coeff': 3}],
  'ratio_beyond_r_sigma': [{'r': 0.5},
   {'r': 3},
   {'r': 1.5},
   {'r': 2},
   {'r': 1},
   {'r': 2.5}],
  'change_quantiles': [{'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.4},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': False, 'qh': 0.6, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.2},
   {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.6},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.2},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.4, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
   {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.4},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.4},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.4, 'ql': 0.2},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': False, 'qh': 0.8, 'ql': 0.4},
   {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'var', 'isabs': False, 'qh': 0.8, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.2},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.4},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.0}],
  'agg_autocorrelation': [{'f_agg': 'var', 'maxlag': 40},
   {'f_agg': 'median', 'maxlag': 40},
   {'f_agg': 'mean', 'maxlag': 40}],
  'fft_coefficient': [{'coeff': 9, 'attr': 'angle'},
   {'coeff': 5, 'attr': 'angle'},
   {'coeff': 95, 'attr': 'abs'},
   {'coeff': 10, 'attr': 'real'},
   {'coeff': 97, 'attr': 'abs'},
   {'coeff': 99, 'attr': 'abs'},
   {'coeff': 2, 'attr': 'abs'},
   {'coeff': 97, 'attr': 'imag'},
   {'coeff': 5, 'attr': 'real'},
   {'coeff': 10, 'attr': 'abs'},
   {'coeff': 72, 'attr': 'abs'},
   {'coeff': 5, 'attr': 'imag'},
   {'coeff': 13, 'attr': 'abs'},
   {'coeff': 23, 'attr': 'abs'},
   {'coeff': 70, 'attr': 'abs'},
   {'coeff': 37, 'attr': 'abs'},
   {'coeff': 32, 'attr': 'abs'},
   {'coeff': 56, 'attr': 'abs'},
   {'coeff': 3, 'attr': 'abs'},
   {'coeff': 30, 'attr': 'abs'},
   {'coeff': 35, 'attr': 'abs'},
   {'coeff': 59, 'attr': 'abs'},
   {'coeff': 14, 'attr': 'real'},
   {'coeff': 33, 'attr': 'abs'},
   {'coeff': 51, 'attr': 'abs'},
   {'coeff': 91, 'attr': 'abs'},
   {'coeff': 11, 'attr': 'real'},
   {'coeff': 25, 'attr': 'abs'},
   {'coeff': 52, 'attr': 'abs'},
   {'coeff': 7, 'attr': 'imag'},
   {'coeff': 86, 'attr': 'abs'},
   {'coeff': 77, 'attr': 'abs'},
   {'coeff': 7, 'attr': 'angle'},
   {'coeff': 71, 'attr': 'abs'},
   {'coeff': 63, 'attr': 'abs'},
   {'coeff': 49, 'attr': 'abs'},
   {'coeff': 96, 'attr': 'abs'},
   {'coeff': 20, 'attr': 'imag'},
   {'coeff': 8, 'attr': 'abs'},
   {'coeff': 48, 'attr': 'abs'},
   {'coeff': 6, 'attr': 'abs'},
   {'coeff': 19, 'attr': 'abs'},
   {'coeff': 73, 'attr': 'abs'}],
  'kurtosis': None,
  'partial_autocorrelation': [{'lag': 3},
   {'lag': 4},
   {'lag': 7},
   {'lag': 6},
   {'lag': 9},
   {'lag': 8},
   {'lag': 2},
   {'lag': 1},
   {'lag': 5}],
  'spkt_welch_density': [{'coeff': 5}, {'coeff': 8}],
  'fft_aggregated': [{'aggtype': 'kurtosis'},
   {'aggtype': 'skew'},
   {'aggtype': 'variance'}],
  'agg_linear_trend': [{'f_agg': 'var', 'chunk_len': 50, 'attr': 'rvalue'},
   {'f_agg': 'max', 'chunk_len': 50, 'attr': 'stderr'},
   {'f_agg': 'mean', 'chunk_len': 50, 'attr': 'stderr'}],
  'energy_ratio_by_chunks': [{'num_segments': 10, 'segment_focus': 1},
   {'num_segments': 10, 'segment_focus': 5},
   {'num_segments': 10, 'segment_focus': 2},
   {'num_segments': 10, 'segment_focus': 7},
   {'num_segments': 10, 'segment_focus': 4}],
  'percentage_of_reoccurring_datapoints_to_all_datapoints': None,
  'time_reversal_asymmetry_statistic': [{'lag': 1}, {'lag': 2}, {'lag': 3}],
  'sample_entropy': None,
  'count_below_mean': None,
  'median': None,
  'count_above_mean': None,
  'last_location_of_maximum': None,
  'variance': None,
  'mean_second_derivative_central': None,
  'autocorrelation': [{'lag': 8}, {'lag': 9}, {'lag': 2}],
  'augmented_dickey_fuller': [{'attr': 'teststat'}, {'attr': 'usedlag'}],
  'range_count': [{'max': 1, 'min': -1}],
  'index_mass_quantile': [{'q': 0.1}, {'q': 0.9}],
  'cwt_coefficients': [{'widths': (2, 5, 10, 20), 'coeff': 8, 'w': 5},
   {'widths': (2, 5, 10, 20), 'coeff': 9, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 10, 'w': 5},
   {'widths': (2, 5, 10, 20), 'coeff': 0, 'w': 10},
   {'widths': (2, 5, 10, 20), 'coeff': 7, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 2, 'w': 5},
   {'widths': (2, 5, 10, 20), 'coeff': 0, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 10, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 1, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 5, 'w': 5}],
  'approximate_entropy': [{'m': 2, 'r': 0.9}],
  'first_location_of_maximum': None,
  'number_peaks': [{'n': 1}, {'n': 5}, {'n': 10}, {'n': 3}],
  'longest_strike_below_mean': None,
  'maximum': None,
  'skewness': None,
  'number_cwt_peaks': [{'n': 1}],
  'last_location_of_minimum': None},
 '方向': {'fft_coefficient': [{'coeff': 5, 'attr': 'real'},
   {'coeff': 20, 'attr': 'real'},
   {'coeff': 42, 'attr': 'abs'},
   {'coeff': 91, 'attr': 'abs'},
   {'coeff': 71, 'attr': 'abs'},
   {'coeff': 29, 'attr': 'abs'},
   {'coeff': 39, 'attr': 'abs'},
   {'coeff': 7, 'attr': 'real'},
   {'coeff': 70, 'attr': 'abs'},
   {'coeff': 72, 'attr': 'abs'},
   {'coeff': 73, 'attr': 'abs'},
   {'coeff': 32, 'attr': 'abs'},
   {'coeff': 65, 'attr': 'abs'},
   {'coeff': 10, 'attr': 'real'},
   {'coeff': 1, 'attr': 'abs'},
   {'coeff': 95, 'attr': 'abs'},
   {'coeff': 51, 'attr': 'abs'},
   {'coeff': 5, 'attr': 'abs'},
   {'coeff': 11, 'attr': 'abs'},
   {'coeff': 45, 'attr': 'abs'},
   {'coeff': 24, 'attr': 'abs'},
   {'coeff': 15, 'attr': 'real'},
   {'coeff': 31, 'attr': 'abs'},
   {'coeff': 10, 'attr': 'abs'},
   {'coeff': 60, 'attr': 'abs'},
   {'coeff': 94, 'attr': 'abs'},
   {'coeff': 80, 'attr': 'abs'},
   {'coeff': 5, 'attr': 'angle'},
   {'coeff': 15, 'attr': 'abs'},
   {'coeff': 48, 'attr': 'abs'},
   {'coeff': 79, 'attr': 'abs'},
   {'coeff': 58, 'attr': 'abs'},
   {'coeff': 99, 'attr': 'abs'},
   {'coeff': 57, 'attr': 'abs'},
   {'coeff': 18, 'attr': 'abs'},
   {'coeff': 64, 'attr': 'abs'},
   {'coeff': 61, 'attr': 'abs'},
   {'coeff': 54, 'attr': 'abs'},
   {'coeff': 13, 'attr': 'abs'},
   {'coeff': 56, 'attr': 'abs'},
   {'coeff': 20, 'attr': 'abs'},
   {'coeff': 74, 'attr': 'abs'},
   {'coeff': 21, 'attr': 'abs'},
   {'coeff': 3, 'attr': 'abs'},
   {'coeff': 68, 'attr': 'abs'},
   {'coeff': 53, 'attr': 'abs'},
   {'coeff': 8, 'attr': 'imag'},
   {'coeff': 46, 'attr': 'abs'},
   {'coeff': 97, 'attr': 'abs'},
   {'coeff': 12, 'attr': 'abs'},
   {'coeff': 30, 'attr': 'abs'},
   {'coeff': 83, 'attr': 'abs'},
   {'coeff': 8, 'attr': 'abs'},
   {'coeff': 62, 'attr': 'abs'},
   {'coeff': 47, 'attr': 'abs'},
   {'coeff': 88, 'attr': 'abs'},
   {'coeff': 28, 'attr': 'abs'},
   {'coeff': 34, 'attr': 'abs'},
   {'coeff': 43, 'attr': 'abs'},
   {'coeff': 69, 'attr': 'abs'},
   {'coeff': 78, 'attr': 'abs'},
   {'coeff': 10, 'attr': 'imag'},
   {'coeff': 7, 'attr': 'abs'},
   {'coeff': 98, 'attr': 'abs'},
   {'coeff': 90, 'attr': 'abs'},
   {'coeff': 66, 'attr': 'abs'},
   {'coeff': 16, 'attr': 'abs'},
   {'coeff': 5, 'attr': 'imag'},
   {'coeff': 86, 'attr': 'abs'},
   {'coeff': 2, 'attr': 'abs'},
   {'coeff': 50, 'attr': 'abs'},
   {'coeff': 59, 'attr': 'abs'}],
  'quantile': [{'q': 0.9}, {'q': 0.8}, {'q': 0.7}],
  'change_quantiles': [{'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.2},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.6},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.2},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.2},
   {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.4},
   {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.6},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.0},
   {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.8},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.4},
   {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.2},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.6},
   {'f_agg': 'var', 'isabs': False, 'qh': 0.2, 'ql': 0.0},
   {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.4},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.2},
   {'f_agg': 'var', 'isabs': False, 'qh': 1.0, 'ql': 0.2},
   {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.4},
   {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.0}],
  'standard_deviation': None,
  'ratio_beyond_r_sigma': [{'r': 0.5}, {'r': 1.5}, {'r': 1}],
  'energy_ratio_by_chunks': [{'num_segments': 10, 'segment_focus': 4}],
  'agg_autocorrelation': [{'f_agg': 'var', 'maxlag': 40},
   {'f_agg': 'median', 'maxlag': 40}],
  'time_reversal_asymmetry_statistic': [{'lag': 1}, {'lag': 3}, {'lag': 2}],
  'agg_linear_trend': [{'f_agg': 'min', 'chunk_len': 5, 'attr': 'intercept'},
   {'f_agg': 'max', 'chunk_len': 10, 'attr': 'rvalue'},
   {'f_agg': 'var', 'chunk_len': 5, 'attr': 'stderr'},
   {'f_agg': 'max', 'chunk_len': 5, 'attr': 'intercept'},
   {'f_agg': 'max', 'chunk_len': 50, 'attr': 'rvalue'},
   {'f_agg': 'max', 'chunk_len': 10, 'attr': 'intercept'},
   {'f_agg': 'max', 'chunk_len': 5, 'attr': 'stderr'},
   {'f_agg': 'var', 'chunk_len': 10, 'attr': 'slope'},
   {'f_agg': 'var', 'chunk_len': 50, 'attr': 'intercept'},
   {'f_agg': 'var', 'chunk_len': 10, 'attr': 'stderr'},
   {'f_agg': 'min', 'chunk_len': 5, 'attr': 'stderr'}],
  'last_location_of_minimum': None,
  'approximate_entropy': [{'m': 2, 'r': 0.1},
   {'m': 2, 'r': 0.9},
   {'m': 2, 'r': 0.3},
   {'m': 2, 'r': 0.5}],
  'partial_autocorrelation': [{'lag': 7},
   {'lag': 8},
   {'lag': 4},
   {'lag': 3},
   {'lag': 5},
   {'lag': 9},
   {'lag': 6}],
  'ratio_value_number_to_time_series_length': None,
  'cwt_coefficients': [{'widths': (2, 5, 10, 20), 'coeff': 4, 'w': 2},
   {'widths': (2, 5, 10, 20), 'coeff': 12, 'w': 10},
   {'widths': (2, 5, 10, 20), 'coeff': 9, 'w': 5}],
  'percentage_of_reoccurring_values_to_all_values': None,
  'number_crossing_m': [{'m': 0}, {'m': 1}],
  'first_location_of_minimum': None,
  'fft_aggregated': [{'aggtype': 'skew'}],
  'ar_coefficient': [{'k': 10, 'coeff': 0},
   {'k': 10, 'coeff': 1},
   {'k': 10, 'coeff': 4},
   {'k': 10, 'coeff': 3}],
  'last_location_of_maximum': None,
  'autocorrelation': [{'lag': 1}],
  'longest_strike_below_mean': None,
  'index_mass_quantile': [{'q': 0.2}],
  'spkt_welch_density': [{'coeff': 5}, {'coeff': 2}],
  'percentage_of_reoccurring_datapoints_to_all_datapoints': None,
  'kurtosis': None,
  'sample_entropy': None,
  'binned_entropy': [{'max_bins': 10}],
  'count_below_mean': None,
  'mean_abs_change': None,
  'linear_trend': [{'attr': 'pvalue'}],
  'cid_ce': [{'normalize': True}],
  'count_above_mean': None}}